# Generated by Django 4.2.2 on 2023-11-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_passenger_passengerinfo_stations_trains_delete_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebrochure2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='', max_length=25, unique=True)),
                ('state_capital', models.CharField(default='Capital : ', max_length=25)),
                ('gnrl_desc', models.TextField(default='')),
                ('places_to_visit', models.TextField(default='')),
                ('time_to_visit', models.TextField(default='')),
                ('climate', models.TextField(default='')),
                ('culture', models.TextField(default='')),
                ('famous_foods', models.TextField(default='')),
                ('imgs', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
