# Generated by Django 4.2.2 on 2023-11-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_ebrochure2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebrochure2',
            name='climate',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='ebrochure2',
            name='culture',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='ebrochure2',
            name='famous_foods',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='ebrochure2',
            name='gnrl_desc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='ebrochure2',
            name='places_to_visit',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='ebrochure2',
            name='state',
            field=models.CharField(blank=True, default='', max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ebrochure2',
            name='state_capital',
            field=models.CharField(blank=True, default='Capital : ', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ebrochure2',
            name='time_to_visit',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
