# Generated by Django 4.2.2 on 2023-11-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_ebrochure2_climate_alter_ebrochure2_culture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebrochure2',
            name='imgs',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
