# Generated by Django 4.2.2 on 2023-11-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_ebrochure2_imgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebrochure2',
            name='imgs',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
